"""
mesh_utils.py
=============
Everything that happens to a mesh *after* it has been generated by either
sdf_core.sdf_to_mesh or csg_core.to_trimesh, and *before* it is trusted
enough to hand to a physics engine:

    1. Verify it is watertight (closed, 2-manifold, consistently wound).
    2. If it isn't, attempt automatic repair and re-verify.
    3. Compute mass properties (volume, center of mass, inertia tensor) so
       gazebo_export.py can write correct <inertial> tags instead of the
       common placeholder of "just use a unit box inertia and hope".
    4. Export/import STL.

WHY THIS MATTERS: a non-watertight mesh (a hole, a flipped face, a
duplicated/zero-area triangle) is invisible to the human eye in a screenshot
but will make a physics engine's collision solver behave unpredictably --
objects fall through each other, inertia is nonsensical, contact resolution
jitters. Every part must pass `check_watertight` before it is allowed into
gazebo_export.py; treat a "not watertight" result as a build error to fix,
not a warning to note and move past.
"""
from __future__ import annotations
from dataclasses import dataclass
import numpy as np
import trimesh


@dataclass
class WatertightReport:
    name: str
    is_watertight: bool
    is_winding_consistent: bool
    euler_number: int
    n_vertices: int
    n_faces: int
    n_open_edges: int
    repaired: bool = False
    notes: str = ""

    def __str__(self):
        status = "PASS" if self.is_watertight else "FAIL"
        rep = " (after auto-repair)" if self.repaired else ""
        return (f"[{status}]{rep} {self.name}: {self.n_vertices}v/{self.n_faces}f, "
                f"euler={self.euler_number}, open_edges={self.n_open_edges}"
                f"{' -- ' + self.notes if self.notes else ''}")


def _open_edge_count(mesh: trimesh.Trimesh) -> int:
    # Edges belonging to exactly one triangle are boundary/open edges. A
    # closed manifold has none.
    unique, counts = np.unique(mesh.edges_sorted, axis=0, return_counts=True)
    return int(np.sum(counts == 1))


def check_watertight(mesh: trimesh.Trimesh, name="part") -> WatertightReport:
    return WatertightReport(
        name=name,
        is_watertight=bool(mesh.is_watertight),
        is_winding_consistent=bool(mesh.is_winding_consistent),
        euler_number=int(mesh.euler_number),
        n_vertices=len(mesh.vertices),
        n_faces=len(mesh.faces),
        n_open_edges=_open_edge_count(mesh),
    )


def repair_and_verify(mesh: trimesh.Trimesh, name="part") -> tuple[trimesh.Trimesh, WatertightReport]:
    """Try trimesh's standard repair pipeline, then re-check. Returns the
    (possibly-repaired) mesh and its final report. Raise-worthy failure is
    left to the caller: this function never raises, it just tells you
    honestly whether the result is trustworthy."""
    report = check_watertight(mesh, name)
    if report.is_watertight and report.is_winding_consistent:
        return mesh, report

    mesh = mesh.copy()
    mesh.merge_vertices()
    mesh.remove_duplicate_faces()
    mesh.remove_degenerate_faces()
    trimesh.repair.fix_normals(mesh)
    trimesh.repair.fix_winding(mesh)
    trimesh.repair.fill_holes(mesh)

    new_report = check_watertight(mesh, name)
    new_report.repaired = True
    if not new_report.is_watertight:
        new_report.notes = (
            "Automatic repair could not close every hole -- this usually means "
            "the source SDF/CSG had a genuine topological problem (e.g. two "
            "shapes that only touch at a single point/edge). Re-examine the "
            "part's construction rather than shipping this mesh."
        )
    return mesh, new_report


def mass_properties(mesh: trimesh.Trimesh, density=1000.0):
    """Volume, mass, center of mass, and inertia tensor (about the center of
    mass, in the mesh's own local frame) for a watertight mesh. Density
    defaults to water (1000 kg/m^3) purely as a neutral placeholder -- pass
    the real material density (e.g. ~2700 for aluminium, ~1200 for ABS/PLA)
    when it matters for the simulated dynamics.

    Returns a dict ready to drop into gazebo_export's <inertial> writer.
    """
    if not mesh.is_watertight:
        raise ValueError(
            "Refusing to compute mass properties on a non-watertight mesh -- "
            "volume/inertia are meaningless without a closed surface. Run "
            "repair_and_verify first."
        )
    m = mesh.copy()
    m.density = density
    return {
        "volume": float(m.volume),
        "mass": float(m.mass),
        "center_mass": m.center_mass.tolist(),
        "inertia": m.moment_inertia.tolist(),  # 3x3 about center_mass, mesh frame
    }


def export_stl(mesh: trimesh.Trimesh, path: str):
    mesh.export(path, file_type="stl")
    return path


def load_stl(path: str) -> trimesh.Trimesh:
    return trimesh.load(path, file_type="stl", process=True)


def union_watertight(meshes: list[trimesh.Trimesh]) -> trimesh.Trimesh:
    """Boolean-union a list of already-watertight trimesh meshes into one
    solid, via manifold3d (imported lazily to avoid a hard dependency loop
    with csg_core). Use this when several parts are meant to be rigidly
    welded into a single physical body (e.g. fusing small fillets/bosses
    onto a main part) rather than connected by a joint."""
    import csg_core as csg
    manifolds = [csg.from_trimesh(m) for m in meshes]
    fused = csg.union(*manifolds)
    return csg.to_trimesh(fused)
