export const ACCEPTED_IMAGE_TYPES = ["image/png", "image/jpeg", "image/gif", "image/webp"]
export const ACCEPTED_FILE_TYPES = [...ACCEPTED_IMAGE_TYPES, "application/pdf"]

export const PLACEHOLDERS = [
    "Fix a TODO in the codebase",
    "What is the tech stack of this project?",
    "Fix broken tests",
    "Explain how authentication works",
    "Find and fix security vulnerabilities",
    "Add unit tests for the user service",
    "Refactor this function to be more readable",
    "What does this error mean?",
    "Help me debug this issue",
    "Generate API documentation",
    "Optimize database queries",
    "Add input validation",
    "Create a new component for...",
    "How do I deploy this project?",
    "Review my code for best practices",
    "Add error handling to this function",
    "Explain this regex pattern",
    "Convert this to TypeScript",
    "Add logging throughout the codebase",
    "What dependencies are outdated?",
    "Help me write a migration script",
    "Implement caching for this endpoint",
    "Add pagination to this list",
    "Create a CLI command for...",
    "How do environment variables work here?",
]
