export namespace Flag {
  export const ATOMCLI_AUTO_SHARE = truthy("ATOMCLI_AUTO_SHARE")
  export const ATOMCLI_GIT_BASH_PATH = process.env["ATOMCLI_GIT_BASH_PATH"]
  export const ATOMCLI_CONFIG = process.env["ATOMCLI_CONFIG"]
  export const ATOMCLI_CONFIG_DIR = process.env["ATOMCLI_CONFIG_DIR"]
  export const ATOMCLI_CONFIG_CONTENT = process.env["ATOMCLI_CONFIG_CONTENT"]
  export const ATOMCLI_INSTALL_DIR = process.env["ATOMCLI_INSTALL_DIR"]
  export const ATOMCLI_DISABLE_AUTOUPDATE = truthy("ATOMCLI_DISABLE_AUTOUPDATE")
  export const ATOMCLI_DISABLE_PRUNE = truthy("ATOMCLI_DISABLE_PRUNE")
  export const ATOMCLI_DISABLE_TERMINAL_TITLE = truthy("ATOMCLI_DISABLE_TERMINAL_TITLE")
  export const ATOMCLI_PERMISSION = process.env["ATOMCLI_PERMISSION"]
  export const ATOMCLI_DISABLE_DEFAULT_PLUGINS = truthy("ATOMCLI_DISABLE_DEFAULT_PLUGINS")
  export const ATOMCLI_DISABLE_LSP_DOWNLOAD = truthy("ATOMCLI_DISABLE_LSP_DOWNLOAD")
  export const ATOMCLI_ENABLE_EXPERIMENTAL_MODELS = truthy("ATOMCLI_ENABLE_EXPERIMENTAL_MODELS")
  export const ATOMCLI_DISABLE_AUTOCOMPACT = truthy("ATOMCLI_DISABLE_AUTOCOMPACT")
  export const ATOMCLI_DISABLE_MODELS_FETCH = truthy("ATOMCLI_DISABLE_MODELS_FETCH")
  export const ATOMCLI_DISABLE_CLAUDE_CODE = truthy("ATOMCLI_DISABLE_CLAUDE_CODE")
  export const ATOMCLI_DISABLE_CLAUDE_CODE_PROMPT =
    ATOMCLI_DISABLE_CLAUDE_CODE || truthy("ATOMCLI_DISABLE_CLAUDE_CODE_PROMPT")
  export const ATOMCLI_DISABLE_CLAUDE_CODE_SKILLS =
    ATOMCLI_DISABLE_CLAUDE_CODE || truthy("ATOMCLI_DISABLE_CLAUDE_CODE_SKILLS")
  export const ATOMCLI_FAKE_VCS = process.env["ATOMCLI_FAKE_VCS"]
  export const ATOMCLI_CLIENT = process.env["ATOMCLI_CLIENT"] ?? "cli"

  // Experimental
  export const ATOMCLI_EXPERIMENTAL = truthy("ATOMCLI_EXPERIMENTAL")
  export const ATOMCLI_EXPERIMENTAL_FILEWATCHER = truthy("ATOMCLI_EXPERIMENTAL_FILEWATCHER")
  export const ATOMCLI_EXPERIMENTAL_DISABLE_FILEWATCHER = truthy("ATOMCLI_EXPERIMENTAL_DISABLE_FILEWATCHER")
  export const ATOMCLI_EXPERIMENTAL_ICON_DISCOVERY =
    ATOMCLI_EXPERIMENTAL || truthy("ATOMCLI_EXPERIMENTAL_ICON_DISCOVERY")
  export const ATOMCLI_EXPERIMENTAL_DISABLE_COPY_ON_SELECT = truthy("ATOMCLI_EXPERIMENTAL_DISABLE_COPY_ON_SELECT")
  export const ATOMCLI_ENABLE_EXA =
    truthy("ATOMCLI_ENABLE_EXA") || ATOMCLI_EXPERIMENTAL || truthy("ATOMCLI_EXPERIMENTAL_EXA")
  export const ATOMCLI_EXPERIMENTAL_BASH_MAX_OUTPUT_LENGTH = number("ATOMCLI_EXPERIMENTAL_BASH_MAX_OUTPUT_LENGTH")
  export const ATOMCLI_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS = number("ATOMCLI_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS")
  export const ATOMCLI_EXPERIMENTAL_OUTPUT_TOKEN_MAX = number("ATOMCLI_EXPERIMENTAL_OUTPUT_TOKEN_MAX")
  export const ATOMCLI_EXPERIMENTAL_OXFMT = ATOMCLI_EXPERIMENTAL || truthy("ATOMCLI_EXPERIMENTAL_OXFMT")
  export const ATOMCLI_EXPERIMENTAL_LSP_TY = truthy("ATOMCLI_EXPERIMENTAL_LSP_TY")
  export const ATOMCLI_EXPERIMENTAL_LSP_TOOL = ATOMCLI_EXPERIMENTAL || truthy("ATOMCLI_EXPERIMENTAL_LSP_TOOL")

  function truthy(key: string) {
    const value = process.env[key]?.toLowerCase()
    return value === "true" || value === "1"
  }

  function number(key: string) {
    const value = process.env[key]
    if (!value) return undefined
    const parsed = Number(value)
    return Number.isInteger(parsed) && parsed > 0 ? parsed : undefined
  }
}
